"""Move vendor to TeaReview model with default

Revision ID: d43fc4f834f1
Revises: 
Create Date: 2024-11-25 19:34:17.719044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd43fc4f834f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_tea')
    with op.batch_alter_table('tea', schema=None) as batch_op:
        batch_op.drop_column('vendor')

    with op.batch_alter_table('tea_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tea_review', schema=None) as batch_op:
        batch_op.drop_column('vendor')

    with op.batch_alter_table('tea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor', sa.VARCHAR(length=100), nullable=False))

    op.create_table('_alembic_tmp_tea',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('producer', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tea_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
